### PR TITLE
Website fixes

### PR DESCRIPTION
**Pull request by Tnixc**
# Issues with current design

SCR-20221222-rxm
SCR-20221222-rvs
SCR-20221222-rv8

# New design

SCR-20221222-rxz

SCR-20221222-s2f
c-9813-a755369ee183.png)

I've also added smooth scrolling for the community tab, and some other effects and indicators.

I've placed the download button on the top right as a very clear call to action button. I've also enlarged the button for github as it's the one users are quite likely to look for. I've also slimmed down the donate button because it causes confusion with the download button and it makes users slow down, having an overall less fluid experience. 

Another obvious change is blurring the background. This is for more distinction between the background and foreground. I've seen another background be suggested in other pr's so it's easy to change.

One important thing to note is the addition of a secondary color. In UI design it's bad practice to use the same color for the heading and body/subtitle as it establishes no visual hierarchy and is slower to read.

I've also made the navbar sticky for obvious reasons.
 
Here's a short video.

https://user-images.githubusercontent.com/85466117/209136613-93af3f83-e2d4-44eb-8b99-8cc2bee48145.mov

### CODE REVIEW

**Comment by DioEgizio** [comment]
This is very broken on mobile, plz fix

**Comment by Tnixc** [comment]
Oh yes I'll fix the mobile version rn.

**Comment by Scrumplex** [comment]
This looks very interesting!

Some things I have noticed in my first impressions:

- Buttons should react when hovering over them
- The background should fill the whole screen (right now it starts ~200px below the top edge)
- The background shouldn't really be blurred, as it causes the edges to be get lighter. Maybe use `backdrop-filter` instead
- The GitHub button should look behave like the other two buttons, and should be grouped with `Donate`
- The downloads page now has two active tab indicators (background and underline)
- Footer shouldn't have so much whitespace between text and a button

**Comment by Scrumplex** [comment]
One small thing: The underline indicators on the nav bar are not clickable, but they highlight the link itself when hovering.

Instead of having that ::after outside of the link itself, you should maybe increase the line-height of the link and position the line within that empty vertical space.

I modified these styles in my devtools to achieve this (marked the changes with a comment):
```css
.nav-item > a {
  color: var(--secondary-text);
  transition: 150ms;
  line-height: 2;  /* new */
}

.home > picture::after, .nav-item::after {
  content: '';
  width: 0%;
  height: 15%; /* changed */
  background: linear-gradient(to right,var(--link),var(--link-light));
  position: absolute;
  bottom: 0; /* changed */
  border-radius: 100vh;
  left: 0;
  transition: 150ms ease-in-out;
  z-index: -1; /* new */
}
```

**Comment by Tnixc** [comment]
I've made the changes. I think we need significant work for a mobile friendly design.

**Comment by TayouVR** [comment]
I personally think the blur is too much or shouldn't be at all... it kinda hides what the image in the background is too much.
Though that might just be my personal taste.

I also feel the download buttons with the gradient + border looks a bit odd, imo it should be a gradient on the border too, or no gradient at all
image

oh and inconsistent spacing as pointed out in the original post... 
image
the right side has less spacing than top, bottom and left

**Comment by Tnixc** [comment]
Got it. As a side note, wouldn't a single line logo work better with this design?

**Comment by Tnixc** [comment]
I've reworked all of the css for the navbar. Spacing is now consistent. (background made cyan for contrast)
SCR-20221223-mfu

**Comment by DioEgizio** [comment]
huh

huh (Firefox mobile btw)

**Comment by Tnixc** [comment]
> huh
> 
> 
> 
> huh (Firefox mobile btw)
> 
> 

Yeah mobile is actual pain. I'm thinking of cloning the design on modrinth and having a whole separate section in the html for the mobile menu.

**Comment by DioEgizio** [comment]
You committed DS_Store 👀

**Comment by DioEgizio** [comment]
I don't like this :/. Could you do smth like the modrinth website?
modrinth

**Comment by Tnixc** [comment]
image

**Comment by ZekeSmith** [comment]
This seems like a rather big redesign and doesnt follow any of the existing internal logic which is understandable as it isnt well documented however the excessive usage of overiding classes with !important and complicated fuctions to address specific elements. There is a lot of changes in this and I will go over direct comments once I am on my desktop. However a greater focus on consistency and atomic design would help a lot more in the long term. I am working on some new features for the website at the moment and you have definetly brought this to my attention and I do like the idea behind it. I'll have a look over implementing this however I might just fix the direct issues instead of focusing on this redesign such as the margin issues outlined. 

If we do want to go along with a navbar redesign I highly suggest you make sure not to use !important, keep to consistent color values (I am in the process of converting to hsl and adding darken functions) I noticed you changed #fff to #ffffff which I guess can make sense but isnt needed. Also using rgb() when there is already hsl() and hex values. 

This is a rather informal review and may come across rather blunt, I plan to properly review it when I am back to working on the website in the next few days. Great work with what you have done so far!

**Comment by Tnixc** [comment]
Thanks for the advice. There's still a lot to be redone and a design system is quite important as right now plenty of values are arbitrary. Maybe we can consider some values from something like tailwind.

**Comment by ZekeSmith** [comment]
I am not a huge fan of using something like Tailwind I think its not necessary for something like this and blocks contribution to users without experience in the framework. It would make more sense to have more universal and better classes as well as some css functions for things such as button darkening. Things that I will need to look into are making sure that I update older code to be more atomic, start using more reusable components. Navbar is a big focus and I appreciate the work your doing, however I would highly recommend you take a more mobile first approach. I don't think I will fully merge this PR there is far to many changes that can also break other things and it would not be fair to put more work on you. This has brought valuable discussion and addressed a fair amount of issues that exist though so some of it will definitely be merged or taken into consideration for future changes.

**Comment by jtrosclairson91** [comment]
Hi,
Meates here,
I was also facing the same problem on my website (https://lemotwordle.com/) but when i update latest version of wordpress the issue resolved automatically. Update latest may be your issue be resolved.

**Comment by ZekeSmith** [comment]
> Hi, Meates here, I was also facing the same problem on my website (https://lemotwordle.com/) but when i update latest version of wordpress the issue resolved automatically. Update latest may be your issue be resolved.

We don't use wordpress but thanks for the input.

**Comment by TayouVR** [comment]
considering the website has undergone various changes since, is this still relevant?

**Pull request closed without merging**
