### PR TITLE
add qt5 and nightly packages for rhel/fedora

### PR DESCRIPTION
**Pull request by getchoo**
I recently added qt5 and nightly builds to my copr repository. they will be on terra soon as well, i'll make another PR when they're ready

### CODE REVIEW

**Review by AshtakaOOf — APPROVED** [review]
I approve this cool PR

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Comment by Scrumplex** [comment]
You might wanna add the nightly package as badges to the README of the main project as well. See https://github.com/PrismLauncher/PrismLauncher

**Comment by AshtakaOOf** [comment]
I can do that if you want

**Pull request merged**
