### PR TITLE
Use pi-apps package json instead of runkit

### PR DESCRIPTION
**Pull request by theofficialgman**
Signed-off-by: theofficialgman <28281419+theofficialgman@users.noreply.github.com>

### CODE REVIEW

**Comment by theofficialgman** [comment]
@Scrumplex runkit couldn't solve the random issues that caused my script to not run half of the time.
So I implemented a packaging database for pi-apps that other projects (like shields.io) can read directly for relavent information.
In the case of the prismlauncher website, it reads the current version.

**Review by txtsd — APPROVED** [review]
LGTM

**Review by Scrumplex — COMMENTED** [review]
That image string is kinda huge :/

**Comment by theofficialgman** [comment]
> That image string is kinda huge :/

Yeah I know, not really anything I can do about it. It's all one line at least so shouldn't really bother anyone.

**Comment by Scrumplex** [comment]
maybe @ZekeSmith has an idea?

My best guess would be creating an icon that's simpler, so that we don't need such a large PNG.

**Comment by theofficialgman** [comment]
> My best guess would be creating an icon that's simpler, so that we don't need such a large PNG.

It's already a really small png. It's only 48x48 pixels. It's the pi-apps logo, there really aren't any substitutes. The original is a quite large svg (like 14KB). I already had to do a lot of shrinking in order to get it under the 8K max size that can be sent in one request to shields.io.

Would you rather just not have the icon?

**Comment by Scrumplex** [comment]
In that case I would prefer to have no logo at all. 
We don't have logos for the other badges as well

**Review by txtsd — APPROVED** [review]

**Pull request merged**
