### PR TITLE
feat: update command-line-interface to match cli

### PR DESCRIPTION
**Pull request by tonyaellie**

### CODE REVIEW

**Comment by txtsd** [comment]
Could you rebase this on `main` and make it match with `prismlauncher`'s current cli output?

**Review by Scrumplex — APPROVED** [review]

**Review by txtsd — COMMENTED** [review]
This is what I see:

```
λ prismlauncher --help
Usage: prismlauncher [options]
Prism Launcher

Options:
  -d, --dir <directory>    Use a custom path as application root (use '.' for
                           current directory)
  -l, --launch <instance>  Launch the specified instance (by instance ID)
  -s, --server <address>   Join the specified server on launch (only valid in
                           combination with --launch)
  -a, --profile <profile>  Use the account specified by its profile name (only
                           valid in combination with --launch)
  --alive                  Write a small 'live.check' file after the launcher
                           starts
  -I, --import <file>      Import instance from specified zip (local path or
                           URL)
  --show <show>            Opens the window for the specified instance (by
                           instance ID)
  -h, --help               Displays help on commandline options.
  --help-all               Displays help, including generic Qt options.
  -v, --version            Displays version information.
```

**Comment by tonyaellie** [comment]
Yea it has the same options but different order, can't remember why so ill just make them match, should i keep the `prismlauncher [-h] [-v] [-d &lt;dir&gt;] [-l &lt;launch&gt;] [-s &lt;server&gt;] [-a &lt;profile&gt;] [-I &lt;import&gt;] [--show &lt;show&gt;] [--alive] [--help-all]` or switch it to just be `prismlauncher [options]`?

**Comment by txtsd** [comment]
Make it match, please. Those look helpful though. I'll check the code to see why it was removed in a bit.

**Review by txtsd — APPROVED** [review]

**Comment by txtsd** [comment]
Thanks!

**Pull request merged**
