### PR TITLE
Simplify Fedora download instructions

### PR DESCRIPTION
**Pull request by jn64**
See #113 for justification.

~Since there was no feedback there, I propose removing Terra entirely until a better solution is provided by anyone else.~ The PR was updated to reflect the discussion on the mentioned issue.

### CODE REVIEW

**Comment by getchoo** [comment]
```diff
diff --git a/src/download/linux.md b/src/download/linux.md
index 44cdeda..aeaf173 100644
--- a/src/download/linux.md
+++ b/src/download/linux.md
@@ -197,7 +197,9 @@ NOTE: Only supports Debian/Raspbian/Pi OS Buster and newer and Ubuntu 18.04 and

 ## Copr

-RPM packages are available on [Copr](https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/).
+RPM packages for Fedora are available on [Copr](https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/).
+
+Nightly builds are updated in the [Terra repository](https://terra.fyralabs.com/) and built on Copr every 24 hours.

 ```bash
 # enables the copr repo
 ```

**Comment by jn64** [comment]
Thanks, updated PR. [Direct link to updated preview](https://deploy-preview-181--prismlauncher.netlify.app/download/linux/#fedora)

We could also merge Fedora and CentOS/RHEL sections at this point (or leave it for another discussion). Only difference from Fedora section is the EPEL line, which IMO should point to [upstream EPEL docs](https://docs.fedoraproject.org/en-US/epel/#_quickstart) rather than the RedHat advertorial.

**Comment by getchoo** [comment]
yeah those would both be great changes :)

might be out of scope for this PR, but i already have a diff for it if a maintainer is good with it being added here

**Review by flowln — APPROVED** [review]
lgtm, thanks!

feel free to create another PR for the Fedora / CentOS / RHEL sections thingy, i think it's a bit cleaner to separate that from this one :)

**Pull request merged**
